Add study discovery validation
NAU-SuperGeeks/geeksurvey pull request #19
Opened 2022-02-11 19:02 UTC by kyleaustria8

The web page only shows users, studies that have not expired. Added functionality for enrollment so that users can only enroll in studies that they are eligible for.

2022-02-11 19:06 UTC, GustavoMiguelValencia requested changes, later dismissed

2022-02-11 19:06 UTC, GustavoMiguelValencia commented on geeksurvey/models.py
> +           print("CANT ENROLL")
Remove print statement

2022-02-11 19:06 UTC, GustavoMiguelValencia commented on geeksurvey/models.py
> +        print("CAN ENROLL")
Remove print statement

2022-02-12 17:52 UTC, timgiroux commented
I'll just merge this and remove those prints on a separate commit so I can get started on more changes without worrying about conflicts.

2022-02-12 17:53 UTC, timgiroux approved these changes

2022-02-12 17:54 UTC, merged