External Payments
NAU-SuperGeeks/geeksurvey pull request #27
Opened 2022-02-25 21:20 UTC by timgiroux

Profile page now has two buttons:
Fund Account, and Remove Funds

These buttons point at new views that access the PayPal sandbox.

*Fund Account* links to a page with a PayPal button, users are redirected to PayPal where they authenticate, and pay $125. They are redirected to GeekSurvey, where their account balance has increased by $100.

*Remove Funds* links to a page where users can submit a form containing a receiver email address (corresponding to a PayPal account). Upon submitting the form, our backend uses the *requests* library to talk to PayPals Sandbox REST API. Here, we use hidden credentials to claim an access_token, and then use the access_token to send a transaction to the user-specified receiver email address. The users PayPal account receives the full amount of their profile balance, and their profile balance is reset to $0.

2022-02-25 21:35 UTC, timgiroux commented on geeksurvey/views.py
> +            # TODO get this from decouple config
forgot to remove this TODO

2022-02-25 21:36 UTC, timgiroux commented on geeksurvey/views.py
> +    # in IPN, set their balance to 0
not in IPN, we just do that here in the same function since these payments always go through on sandbox

2022-02-25 21:38 UTC, timgiroux commented on geeksurvey/views.py
> +        rb = requests.post(PAYOUT_URL, data=json.dumps(payload), headers=head)
rename rb

2022-02-25 21:38 UTC, timgiroux commented on geeksurvey/views.py
> +        r = requests.post(TOKEN_URL, data=payload, headers=headers, auth=(CLIENT_ID,CLIENT_SECRET))
rename r

2022-02-25 21:38 UTC, timgiroux commented on geeksurvey/views.py
> +
too much whitespace around here

2022-02-25 22:10 UTC, GustavoMiguelValencia requested changes

2022-02-25 22:10 UTC, GustavoMiguelValencia commented on geeksurvey/views.py
> +        if profile.balance < 5:
May want to add comment giving context as to why 5 was chosen. While it's probably a good value to restrict minimum payouts, it does currently seem somewhat arbitrary.

2022-02-25 22:10 UTC, GustavoMiguelValencia commented on geeksurvey/views.py
> +        payment = Payment(owner=request.user, amount=-1*profile.balance)
May want to put ```-1*profile.balance``` in parenthesis to avoid potential at-a-glance confusion with the subtraction assignment operator (```-=```).

2022-02-26 18:33 UTC, GustavoMiguelValencia approved these changes

2022-02-26 18:33 UTC, merged